// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompleteStatus } from ".\\status\\CompleteStatus";
import type { DeleteStatus } from ".\\status\\DeleteStatus";

export interface Model { id: number, title: string, text: string | null, file_path: string | null, completed_at: string | null, is_completed: CompleteStatus, limit_date: string | null, limit_time: string | null, should_notify: number | null, create_at: string, update_at: string | null, deleted_at: string | null, is_deleted: DeleteStatus, }