// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Completed } from ".\\status\\CompleteStatus";
import type { Deleted } from ".\\status\\DeleteStatus";
import type { ShouldNotify } from ".\\status\\ShouldNotify";

export interface Model { id: number, title: string, text: string | null, file_path: string | null, completed_at: string | null, is_completed: Completed, limit_date: string | null, limit_time: string | null, should_notify: ShouldNotify | null, create_at: string, update_at: string | null, deleted_at: string | null, is_deleted: Deleted, }